### ISSUE TITLE
optimize performance

### ISSUE THREAD

**Issue by heikog** [heikog/mission2mars#6]
framerate must not be below 72 fps minimum at any time. 90 fps should be the goal
https://developer.oculus.com/documentation/native/android/mobile-draw-call-analysis/
https://developer.oculus.com/documentation/native/android/po-perf-opt-mobile/
https://aj-21683.medium.com/tips-and-tricks-for-oculus-quest-development-with-unreal-engine-4-25-3-4f743e973434

https://docs.unrealengine.com/4.26/en-US/SharingAndReleasing/XRDevelopment/VR/DevelopVR/ContentSetup/

**Comment by dscgi** [comment]
solved
